### ISSUE TITLE
Sheets & Slides printjob titles inaccurate.

### ISSUE THREAD

**Issue by Jezternz** [salmonthinlion/GoogleCloudPrintApi#10]
There appears to be an issue when submitting documents that are created in google sheets or google slides:

- Document Created in Google Documents "Example Name 1" -> Title = "Example Name 1"
- Document Created in Google Sheets "Example Name 2" -> Title = "export"
- Document Created in Google Slides "Example Name 3" -> Title = "pdf"

Not sure if this is a problem with google, or the API. If it is with google, I am happy to raise the issue with google.

**Comment by salmonthinlion** [comment]
Hi J,

It should be an issue from google. I have previously use this library in a project for getting documents submitted from different mobile apps (not only from google). It turns out some document's name were modified by the app itself, our library is passive to the change the app makes, and we only know the document's name by what google tells. I think you may raise an issue to google for this =)

Btw, I would like to know if it is ok to integrate your XMPP code for job notice to this library? I am going to work it on my own if you are busy with other things. It would be nice if you are ok with that =) 

Best,
Karl

**Comment by Jezternz** [comment]
Hi Karl,

Thanks for the heads up, I will report to google. I thought you just passively passed on the title, but I thought maybe for slides etc there are other fields that better represent the title. Either way I will raise to google.

Regarding XMPP code, I am sorry I haven't had time to look at integrating and creating a push request myself, I have been swamped with different projects. Please feel free to integrate the XMPP code.

Cheers,
Josh

**Comment by Jezternz** [comment]
For reference, I have re-posted this query here: https://groups.google.com/forum/#!topic/gcp-developers/BFKRsMHeyIs

**Comment by salmonthinlion** [comment]
Thanks, J =)
