### ISSUE TITLE
Need to retrieve filesize before download

### ISSUE THREAD

**Issue by Jezternz** [salmonthinlion/GoogleCloudPrintApi#3]
Hi,

I have come across an issue in my own project, being that I want to be able to test the size of a document before I download it.

It sounds like the following basic code will be enough to retrieve the size of a document before download:
```
WebClient client = new System.Net.WebClient();
client.Headers.Add("X-CloudPrint-Proxy", printerProxyId);
client.OpenRead(jobUrl);
Int64 bytes_total = Convert.ToInt64(client.ResponseHeaders["Content-Length"]);
```

Probably worth mentioning, that the above code I believe would work, but when I run it, I get an expected Auth error "403 Forbidden"

Are you able to provide a way to get document size? - or am I able to create a pull request and attempt it myself?

Cheers

**Comment by salmonthinlion** [comment]
Hi J,

A "403 Forbidden" message gives you the fact that your request is unauthorized, you've probably missed out the oauth bearer token in your request. You may want to add
`client.Headers.Add("Authorization", "Bearer <your_oauth_access_token>")` 
in your request before you send out the message.

On the other hand, you can also find your document size by using "Length" property of the stream, you may end up with something like
```
using (var fs = await client.GetDocumentAsync(printJob.FileUrl, proxy)){
    var size = fs.Length; 
    /*blah-blah-blah*/;
}
```
It should probably gives you the length of the document size.

Pull requests are always welcome, that's what open source is. I am open to any pull request that helps others to cater problems!

Best,
Karl

**Comment by Jezternz** [comment]
Maybe I am not understanding properly, but I was under the impression:
```
using (var fs = await client.GetDocumentAsync(printJob.FileUrl, proxy)){
    var size = fs.Length; 
    /*blah-blah-blah*/;
}
```
Would only retrieve the file size after download is complete, where I am looking for the download size before I go to download it.

I have tried updated code below, but still get unauthorized, any ideas?
```
WebClient client = new System.Net.WebClient();
client.Headers.Add("X-CloudPrint-Proxy", printerProxyId);
client.Headers.Add("Authorization", string.Format("Bearer {0}", gcpToken.AccessToken)); 
client.OpenRead(jobUrl);
Int64 bytes_total = Convert.ToInt64(client.ResponseHeaders["Content-Length"]);
MessageBox.Show(bytes_total.ToString() + " Bytes");
```
Thanks for all the help Karl

**Comment by salmonthinlion** [comment]
Hi J,

For the "Length" property, I was making an analogy with FileStream class where the class reads the file's size through the metadata provided by the file system rather than counting the number of bytes in the file. So, the file should not begin reading until the read command is processed. I doubt there is similar behaviour on stream read from response content. But who knows, it depends on Microsoft's implementation, maybe I should try scanning the 'corefx' source code for the answer, haha ;)

Anyway, I have committed another version here which exposes the internal token for the google cloud print client, you can use it for external web call using webclient/httpclient.

```
var googClient = new GoogleCloudPrintClient(provider, token);

using (var client = new WebClient())
{
    client.Headers.Add("X-CloudPrint-Proxy", proxy);
    var authToken = googClient.GetTokenAsync().Result.AccessToken;
    client.Headers.Add("Authorization", string.Format("Bearer {0}", authToken));
    client.OpenRead("https://www.google.com/cloudprint/download?id=71a1c2f9-62a8-884a-a673-114db79b87bf");
    var bytes_total = Convert.ToInt64(client.ResponseHeaders["Content-Length"]);
    Console.WriteLine(bytes_total.ToString() + " Bytes");
}
```

However, it seems that Google does not provide the Content-Length header in the response, what i get is:
```
Pragma: no-cache
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Alt-Svc: quic=":443"; ma=2592000; v="36,35,34"
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/pdf
Date: Tue, 22 Nov 2016 06:19:19 GMT
Expires: Mon, 01 Jan 1990 00:00:00 GMT
P3P: CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."
Set-Cookie: NID=91=pkBHGBsiYAlw8UizO637F0TLKe4oIDKuk42zhkqV7XT_LzxgJyZVs6_BkGnBCldHgaDhHnwHpruKlDaFimltFoDNHRR6b_ftjTbm9FZAg_SSTme5y4h2BdPkXa0ZbBLH;Domain=.google.com;Path=/;Expires=Wed, 24-May-2017 06:19:19 GMT;HttpOnly
Server: GSE
```
You may want to use partial response in order to terminate downloads that are too large. But it requires you download the first n bytes for this case. There should be some other methods to guard, but i can only think of this for now. Hopes you can find a better way to solve this issue =)

Best,
Karl

**Comment by Jezternz** [comment]
Thanks for all the followup help Karl, much appreciated. It looks like this just isn't going to be possible, may have to put in a feature request with Google.
