### ISSUE TITLE
Issues surrounding asynchronous use.

### ISSUE THREAD

**Issue by Jezternz** [salmonthinlion/GoogleCloudPrintApi#7]
Hi Karl,

I have recently gone to move my code from blocking code to asynchronous code like follows:
Example 1 (Result):
```
try
{
     var fetchRequest = new FetchRequest { PrinterId = googlePrinterId };
     var fetchResponse = _gcpClient.FetchJobAsync(fetchRequest).Result;
     Console.WriteLine("(1)");
}
catch(Exception ex)
{
     Console.WriteLine("(2)");
}
```
Example 2 (await):
```
try
{
     var fetchRequest = new FetchRequest { PrinterId = googlePrinterId };
     var fetchResponse = await _gcpClient.FetchJobAsync(fetchRequest);
     Console.WriteLine("(1)");
}
catch(Exception ex)
{
     Console.WriteLine("(2)");
}
```

As this is recommended, given .Result (and .Wait()) are blocking, and await is not blocking.
However I have noticed that this has a strange affect on the stack, and does not behave as expected.

In the examples above, Example 1 will always hit the (1) or (2) depending on whether an exception gets thrown. However in Example 2, the code will never reach (1) or (2).

It seems as though FetchJobAsync() will only work when it is used Synchronously, would it be worth adding test cases for "await".

-- On a side note, I have been playing around with xmpp and have hit a couple of small issues:
1) Oauth scope needs to be: "protected override string Scope => "https://www.googleapis.com/auth/cloudprint https://www.googleapis.com/auth/googletalk";"
2) Using AccessToken appears to work when authenticating against google talk, but RefreshToken does not work, any ideas why? (Examining the strings the formats looked a little different for some reason)

**Comment by Jezternz** [comment]
Looking at the sourcecode, I am wondering if setting ".ConfigureAwait(false);" prevents the method from being used like typical async? Possibly setting this to true may fix the problem, but I do not understand the full ramifications of this.

**Comment by Jezternz** [comment]
I tried removing the ConfigureAwait(false) from all the source code, but this did not help, so I suspect it may just be me doing something silly.

**Comment by Jezternz** [comment]
May still be worth adding a test case for this though, and working out what is going wrong:
```
try
{
     var fetchRequest = new FetchRequest { PrinterId = "NonExistantPrinter"};
     var fetchResponse = await _gcpClient.FetchJobAsync(fetchRequest);
}
catch(Exception ex)
{
     //Assert we hit here.
}
```

**Comment by salmonthinlion** [comment]
Hi J,

For the exception caught case, you may have used void as a return type. But it is recommended to avoid the use of async void because the method will simply returns after the await method fires, exception will not be caught in this case. You should probably change the return type as Task or Task\<T\> . 

For more information, you can find the following resources: [this](http://www.axilis.com/2015/07/27/async-exception-handling-in-c/) and 2nd answer of [this](http://stackoverflow.com/questions/5383310/catch-an-exception-thrown-by-an-async-method
)

For the xmpp implementation, you may help adding the following classes: 
1. public class GoogleTalkForCloudPrintOAuth2Provider : GoogleOAuth2ProviderBase
2. public class GoogleTalkForCloudPrintClient : GoogleClientBase

and follow the patterns in GoogleCloudPrintClient and implement the google talk logic. 

For the RefreshToken, I need some time to study the Google talk xmpp spec before I can try to investigate the issue. May try it this few days.

Best,
Karl

**Comment by Jezternz** [comment]
I created a basic program that establishes a connection via XMPP, it uses the .net45 library, with a single modifcation to GoogleCloudPrintOAuth2Provider.cs, being:
```
protected override string Scope => "https://www.googleapis.com/auth/cloudprint https://www.googleapis.com/auth/googletalk";
```
You will notice the XMPP correctly establishes a connection and subscribes to events when using:
```
var tokenStr = token.AccessToken;
```
But fails when using:
```
var tokenStr = token.RefreshToken;
```

It all seems absolutely fine to me, so must be something funny :s

[GoogleCloudPrintXMPPTester.zip](https://github.com/salmonthinlion/GoogleCloudPrintApi/files/700649/GoogleCloudPrintXMPPTester.zip)

**Comment by salmonthinlion** [comment]
It appears to be another issue, I have moved it to [here](https://github.com/salmonthinlion/GoogleCloudPrintApi/issues/8) and close this issue
